"""init tables

Revision ID: 350347263bdd
Revises: 
Create Date: 2025-10-15 09:36:36.540054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350347263bdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('charge_range', sa.String(length=40), nullable=True),
    sa.Column('mass_gev', sa.Float(), nullable=True),
    sa.Column('genesis_time', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_name'), 'elements', ['name'], unique=False)
    op.create_table('epochs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_norm', sa.Float(), nullable=False),
    sa.Column('end_norm', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epochs_name'), 'epochs', ['name'], unique=True)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epoch_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('time_mark', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_epoch_id'), 'annotations', ['epoch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_epoch_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_epochs_name'), table_name='epochs')
    op.drop_table('epochs')
    op.drop_index(op.f('ix_elements_name'), table_name='elements')
    op.drop_table('elements')
    # ### end Alembic commands ###
